[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Ensure SPA works if you add routes later
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
